### **IMPORT PACKAGES**

In [3]:
import pandas as pd

### **LOAD DATASETS**

In [113]:
nba_teams = pd.read_csv(filepath_or_buffer='Data_NBA_1/nba_teams.csv')
nba_roster = pd.read_csv(filepath_or_buffer='Data_NBA_1/nba_roster.csv')
nba_team_stats = pd.read_csv(filepath_or_buffer='Data_NBA_1/nba_team_stats.csv')
nba_stats = pd.read_csv(filepath_or_buffer='Data_NBA_1/nba_stats.csv')
nba_hall_of_fame = pd.read_csv(filepath_or_buffer='Data_NBA_1/nba_hall_of_fame.csv')

nba_active_teams = pd.read_csv(filepath_or_buffer='Data_NBA_2/nba_active_teams.csv')
nba_defunct_teams = pd.read_csv(filepath_or_buffer='Data_NBA_2/nba_defunct_teams.csv')
nba_players = pd.read_csv(filepath_or_buffer='Data_NBA_2/nba_players.csv')
team_stats = pd.read_csv(filepath_or_buffer='Data_NBA_2/team_stats.csv')
player_stats = pd.read_csv(filepath_or_buffer='Data_NBA_2/player_stats.csv')

In [82]:
nba_teams = nba_teams.loc[:, ['Division', 'Team Name']]
nba_teams['Division'] = nba_teams['Division'].str.title()
nba_teams.rename(columns={'Division': 'division', 'Team Name': 'franchise'}, inplace=True)
nba_teams.head()

   division           franchise
0  Atlantic      Boston Celtics
1  Atlantic       Brooklyn Nets
2  Atlantic     New York Knicks
3  Atlantic  Philadelphia 76ers
4  Atlantic     Toronto Raptors

In [80]:
nba_active_teams = nba_active_teams[nba_active_teams['end_year'] == '2024-25'].drop_duplicates(subset='franchise', ignore_index=True)
nba_active_teams.drop(columns=['league', 'end_year'], inplace=True)
nba_active_teams.head()

,franchise,start_year,year,games,wins,losses,win_loss_percentage,playoff_years,first_place_division,conference_championship_win_years,league_championship_win_years
0,Atlanta Hawks,1949-50,76,5952,2934,3018,0.493,49,12,0,1
1,Boston Celtics,1946-47,79,6129,3646,2483,0.595,61,34,11,18
2,Brooklyn Nets,1967-68,58,4627,2034,2593,0.440,31,5,2,2
3,Charlotte Hornets,1988-89,35,2727,1179,1548,0.432,10,0,0,0
4,Chicago Bulls,1966-67,59,4695,2389,2306,0.509,36,9,6,6

In [84]:
nba_active_teams = nba_teams.merge(right=nba_active_teams, on='franchise')
nba_active_teams.head()

,division,franchise,start_year,year,games,wins,losses,win_loss_percentage,playoff_years,first_place_division,conference_championship_win_years,league_championship_win_years
0,Atlantic,Boston Celtics,1946-47,79,6129,3646,2483,0.595,61,34,11,18
1,Atlantic,Brooklyn Nets,1967-68,58,4627,2034,2593,0.440,31,5,2,2
2,Atlantic,New York Knicks,1946-47,79,6119,2982,3137,0.487,45,8,4,2
3,Atlantic,Philadelphia 76ers,1949-50,76,5954,3103,2851,0.521,54,12,5,3
4,Atlantic,Toronto Raptors,1995-96,30,2325,1099,1226,0.473,13,7,1,1

In [101]:
nba_players

,Name,From,To,Pos,Height,Weight,Birth Date,Colleges,Retired
0,Alaa Abdelnaby,1991,1995,F-C,6-10,240.0,"June 24, 1968",Duke,1
1,Zaid Abdul-Aziz,1969,1978,C-F,6-9,235.0,"April 7, 1946",Iowa State,1
2,Kareem Abdul-Jabbar,1970,1989,C,7-2,225.0,"April 16, 1947",UCLA,1
3,Mahmoud Abdul-Rauf,1991,2001,G,6-1,162.0,"March 9, 1969",LSU,1
4,Tariq Abdul-Wahad,1998,2003,F,6-6,223.0,"November 3, 1974","Michigan, San Jose State",1
...,...,...,...,...,...,...,...,...,...
5280,Ante Žižić,2018,2020,F-C,6-10,266.0,"January 4, 1997",NaN,1
5281,Jim Zoet,1983,1983,C,7-1,240.0,"December 20, 1953",Kent State University,1
5282,Bill Zopf,1971,1971,G,6-1,170.0,"June 7, 1948",Duquesne,1
5283,Ivica Zubac,2017,2025,C,7-0,240.0,"March 18, 1997",NaN,0
5284,Matt Zunic,1949,1949,G-F,6-3,195.0,"December 19, 1919",George Washington,1

In [131]:
nba_players[(nba_players['To'] < 2025) & (nba_players['Retired'] == 0)]

,Name,From,To,Pos,Height,Weight,Birth Date,Colleges,Retired
55,Ty-Shon Alexander,2021,2021,G,6-3,195.0,"July 16, 1998",Creighton,0
59,Rawle Alkins,2019,2019,G,6-5,225.0,"October 29, 1997",Arizona,0
71,Timmy Allen,2024,2024,F,6-6,210.0,"January 9, 2000","Utah, Texas",0
102,Justin Anderson,2016,2022,G,6-6,230.0,"November 19, 1993",Virginia,0
120,Kostas Antetokounmpo,2019,2021,F,6-10,200.0,"November 20, 1997",Dayton,0
...,...,...,...,...,...,...,...,...,...
5240,Justin Wright-Foreman,2020,2020,G,6-0,190.0,"October 27, 1997",Hofstra,0
5251,Gabe York,2022,2023,G,6-3,185.0,"August 2, 1993",Arizona,0
5260,Thaddeus Young,2008,2024,F,6-8,235.0,"June 21, 1988",Georgia Tech,0
5264,Omer Yurtseven,2022,2024,C,7-0,264.0,"June 19, 1998","NC State, Georgetown",0
5267,Cody Zeller,2014,2024,C-F,6-11,240.0,"October 5, 1992",Indiana,0

In [130]:
nba_roster[nba_roster['Player'] == 'Guerschon Yabusele']

,Player,#,Pos,Height,Weight,Birthdate,Age,Exp,School,How Acquired,Team Name,Player Link,Season
274,Guerschon Yabusele,#28,F,6-8,265 lbs,"DEC 17, 1995",29,2,"Rouen, France",Signed on 08/29/24,PHILADELPHIA 76ERS,https://www.nba.com/stats/player/1627824/,2024-25

In [109]:
team_stats[team_stats['Season'].between('2002-2003', '2022-2023')]

,Rk,Team,G,MP,FG,FGA,FG%,3P,3PA,3P%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Season
230,1,Dallas Mavericks,82,19780,3161,6982,0.453,636,1668,0.381,...,912,2544,3456,1837,665,449,949,1730,8444,2002-2003
231,2,Golden State Warriors,82,19755,3061,6941,0.441,425,1235,0.344,...,1284,2546,3830,1712,594,506,1295,1786,8400,2002-2003
232,3,Sacramento Kings,82,19830,3242,6990,0.464,491,1288,0.381,...,900,2751,3651,2034,736,457,1192,1666,8342,2002-2003
233,4,Los Angeles Lakers,82,19930,3091,6856,0.451,486,1367,0.356,...,1078,2554,3632,1909,639,470,1192,1874,8230,2002-2003
234,5,Milwaukee Bucks,82,19905,3045,6670,0.457,585,1526,0.383,...,876,2367,3243,1823,622,344,1044,1820,8158,2002-2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,26,Orlando Magic,82,19780,3323,7074,0.470,883,2551,0.346,...,833,2713,3546,1906,603,382,1236,1652,9136,2022-2023
854,27,Charlotte Hornets,82,19830,3385,7413,0.457,881,2669,0.330,...,901,2751,3652,2062,634,425,1164,1661,9098,2022-2023
855,28,Houston Rockets,82,19755,3329,7287,0.457,856,2619,0.327,...,1100,2695,3795,1835,600,374,1332,1679,9081,2022-2023
856,29,Detroit Pistons,82,19805,3244,7140,0.454,934,2659,0.351,...,916,2564,3480,1884,574,308,1237,1813,9045,2022-2023
857,30,Miami Heat,82,19805,3215,6991,0.460,980,2852,0.344,...,796,2533,3329,1955,655,243,1106,1516,8977,2022-2023

In [55]:
nba_team_stats[nba_team_stats['Year'].between('2002-03', '2022-23')]

,Team Name,Year,Overall -,GP - Games Played,MIN - Minutes Played,PTS - Points,W - Wins,L - Losses,W_PCT - Win Percentage,FGM - Field Goals Made,...,FT_PCT - Free Throw Percentage,OREB - Offensive Rebounds,DREB - Defensive Rebounds,REB - Rebounds,AST - Assists,TOV - Turnovers,STL - Steals,BLK - Blocks,PF - Personal Fouls,PLUS_MINUS - Plus-Minus
2,BOSTON CELTICS,2022-23,2022-23,82,48.7,117.9,57,25,0.695,42.2,...,81.2,9.7,35.6,45.3,26.7,13.4,6.4,5.2,18.8,6.5
3,BOSTON CELTICS,2021-22,2021-22,82,48.5,111.8,51,31,0.622,40.7,...,81.6,10.5,35.5,46.1,24.8,13.6,7.2,5.8,18.5,7.3
4,BOSTON CELTICS,2020-21,2020-21,72,48.3,112.6,36,36,0.500,41.5,...,77.5,10.6,33.6,44.3,23.5,14.1,7.7,5.3,20.4,1.5
5,BOSTON CELTICS,2019-20,2019-20,72,48.4,113.7,48,24,0.667,41.3,...,80.1,10.7,35.4,46.1,23.0,13.8,8.3,5.6,21.6,6.3
6,BOSTON CELTICS,2018-19,2018-19,82,48.2,112.4,49,33,0.598,42.1,...,80.2,9.8,34.7,44.5,26.3,12.8,8.6,5.3,20.4,4.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
851,SAN ANTONIO SPURS,2006-07,2007-08,82,48.1,95.4,56,24,0.707,36.6,...,75.1,9.3,31.4,40.7,22.1,13.9,7.2,5.1,19.4,8.4
852,SAN ANTONIO SPURS,2005-06,2005-06,82,48.3,95.6,63,19,0.768,36.5,...,70.2,10.4,31.1,41.5,20.9,13.7,6.6,5.7,20.9,6.8
853,SAN ANTONIO SPURS,2004-05,2004-05,82,48.3,96.2,59,23,0.720,35.6,...,72.4,12.0,30.4,42.4,21.6,13.7,7.5,6.6,20.9,7.8
854,SAN ANTONIO SPURS,2003-04,2003-04,82,48.2,91.5,57,25,0.695,34.7,...,68.1,12.5,32.5,45.1,20.4,14.7,8.1,6.5,20.3,7.2
855,SAN ANTONIO SPURS,2002-03,2002-03,82,48.4,95.8,60,22,0.732,35.5,...,72.5,11.5,31.2,42.6,20.0,15.8,7.7,6.5,20.4,5.4

In [107]:
nba_stats

,#,PLAYER,TEAM,GP,MIN,PTS,FGM,FGA,FG%,3PM,...,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF,SEASON
0,1,Giannis Antetokounmpo,MIL,23,35.2,32.7,12.8,20.8,61.4,0.1,...,61.5,2.0,9.5,11.5,6.1,0.6,1.6,3.3,36.7,2024-25
1,2,Nikola Jokić,DEN,21,37.3,30.9,11.8,21.1,55.8,2.1,...,79.7,3.8,9.5,13.3,9.9,1.8,0.7,3.9,42.1,2024-25
2,3,Shai Gilgeous-Alexander,OKC,26,34.5,30.5,10.7,20.8,51.3,2.1,...,86.7,0.8,4.7,5.4,6.3,2.0,1.0,2.7,31.3,2024-25
3,4,LaMelo Ball,CHA,20,33.7,30.4,10.5,24.8,42.1,4.5,...,84.0,0.9,4.4,5.3,7.5,1.4,0.2,4.3,25.2,2024-25
4,5,Luka Dončić,DAL,20,37.0,28.9,10.1,21.9,45.9,3.6,...,76.6,0.7,7.9,8.6,8.2,2.1,0.5,3.5,31.3,2024-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,233,Cody Martin,CHA,52,16.3,4.0,1.6,3.6,44.1,0.3,...,58.1,1.0,2.1,3.1,1.7,0.7,0.2,0.8,6.5,2020-21
1211,234,Matisse Thybulle,PHI,65,20.0,3.9,1.6,3.7,42.0,0.7,...,44.4,0.5,1.4,1.9,1.0,1.6,1.1,0.5,6.7,2020-21
1212,235,P.J. Tucker,MIL,52,26.1,3.7,1.3,3.4,37.3,0.8,...,75.0,1.0,2.9,3.9,1.2,0.8,0.4,0.8,6.9,2020-21
1213,236,Thanasis Antetokounmpo,MIL,57,9.7,2.9,1.2,2.4,48.9,0.1,...,51.0,0.9,1.2,2.2,0.8,0.4,0.2,0.8,4.1,2020-21
1214,237,Miye Oni,UTA,54,9.6,1.9,0.6,1.8,35.4,0.6,...,83.3,0.4,1.1,1.6,0.5,0.2,0.1,0.3,2.9,2020-21

In [112]:
player_stats

,Season,Team,Pos,G,GS,MP,FG,FGA,FG%,3P,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Name
0,2020-21,MIA,PF,61.0,4.0,737.0,124.0,228.0,0.544,0.0,...,73.0,135.0,208.0,29.0,20.0,28.0,43.0,91.0,304.0,Precious Achiuwa
1,2021-22,TOR,C,73.0,28.0,1725.0,265.0,603.0,0.439,56.0,...,146.0,327.0,473.0,82.0,37.0,41.0,84.0,151.0,664.0,Precious Achiuwa
2,2022-23,TOR,C,55.0,12.0,1140.0,196.0,404.0,0.485,29.0,...,100.0,228.0,328.0,50.0,31.0,30.0,59.0,102.0,508.0,Precious Achiuwa
3,2023-24,2TM,PF,74.0,18.0,1624.0,235.0,469.0,0.501,26.0,...,191.0,296.0,487.0,97.0,46.0,68.0,83.0,143.0,565.0,Precious Achiuwa
4,2023-24,TOR,C,25.0,0.0,437.0,78.0,170.0,0.459,13.0,...,50.0,86.0,136.0,44.0,16.0,12.0,29.0,40.0,193.0,Precious Achiuwa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5043,2020-21,LAC,C,72.0,33.0,1609.0,257.0,394.0,0.652,1.0,...,189.0,330.0,519.0,90.0,24.0,62.0,81.0,187.0,650.0,Ivica Zubac
5044,2021-22,LAC,C,76.0,76.0,1852.0,310.0,495.0,0.626,0.0,...,217.0,427.0,644.0,120.0,36.0,77.0,114.0,203.0,785.0,Ivica Zubac
5045,2022-23,LAC,C,76.0,76.0,2170.0,326.0,514.0,0.634,0.0,...,236.0,520.0,756.0,77.0,29.0,98.0,117.0,219.0,818.0,Ivica Zubac
5046,2023-24,LAC,C,68.0,68.0,1794.0,337.0,519.0,0.649,0.0,...,196.0,430.0,626.0,93.0,22.0,83.0,79.0,180.0,794.0,Ivica Zubac
5047,2024-25,LAC,C,31.0,31.0,1011.0,213.0,347.0,0.614,0.0,...,122.0,267.0,389.0,77.0,22.0,35.0,59.0,64.0,472.0,Ivica Zubac

In [118]:
stats_per_game = pd.read_csv(filepath_or_buffer='Data_NBA_2/stats_per_game.csv')

In [ ]:
stats_per_game[stats_per_game['Team']]

,Rk,Team,G,MP,FG,FGA,FG%,3P,3PA,3P%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Season
0,1,Orlando Magic,82,243.0,42.2,84.1,0.502,6.4,17.2,0.370,...,14.0,30.0,44.0,27.8,8.2,6.0,15.8,21.0,110.9,1994-1995
1,2,Phoenix Suns,82,241.8,40.9,85.0,0.482,7.1,19.3,0.369,...,12.5,29.3,41.8,26.8,8.4,3.8,14.2,22.4,110.6,1994-1995
2,3,Seattle SuperSonics,82,241.8,40.4,82.2,0.491,6.0,15.9,0.376,...,13.0,28.5,41.5,25.8,11.2,4.8,15.8,25.2,110.4,1994-1995
3,4,San Antonio Spurs,82,242.1,39.5,81.5,0.484,5.3,14.1,0.375,...,12.5,32.5,45.0,23.4,8.0,5.6,15.2,22.8,106.6,1994-1995
4,5,Utah Jazz,82,241.2,39.5,77.3,0.512,3.7,9.8,0.376,...,10.7,29.4,40.1,27.5,9.2,4.8,15.7,24.9,106.4,1994-1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,26,Miami Heat,82,240.9,39.8,85.6,0.465,12.5,33.7,0.370,...,9.3,33.0,42.3,25.8,7.5,3.4,12.7,17.3,110.1,2023-2024
884,27,Detroit Pistons,82,240.9,40.9,88.2,0.463,11.0,31.7,0.348,...,10.5,32.8,43.3,25.5,6.5,4.7,15.2,20.6,109.9,2023-2024
885,28,Charlotte Hornets,82,240.6,40.0,87.0,0.460,12.1,34.0,0.355,...,9.3,31.0,40.3,24.8,6.9,4.5,13.8,18.0,106.6,2023-2024
886,29,Portland Trail Blazers,82,242.4,39.4,89.7,0.439,11.5,33.2,0.345,...,12.6,30.1,42.7,23.1,7.6,4.3,15.2,20.2,106.4,2023-2024
887,30,Memphis Grizzlies,82,241.2,38.4,88.2,0.435,13.1,37.8,0.346,...,10.9,31.7,42.6,24.7,8.2,6.1,15.1,19.1,105.8,2023-2024

In [121]:
stats_per_game['Team'].nunique()

37

In [120]:
nba_team_stats

,Team Name,Year,Overall -,GP - Games Played,MIN - Minutes Played,PTS - Points,W - Wins,L - Losses,W_PCT - Win Percentage,FGM - Field Goals Made,...,FT_PCT - Free Throw Percentage,OREB - Offensive Rebounds,DREB - Defensive Rebounds,REB - Rebounds,AST - Assists,TOV - Turnovers,STL - Steals,BLK - Blocks,PF - Personal Fouls,PLUS_MINUS - Plus-Minus
0,BOSTON CELTICS,2024-25,2024-25,15,49.0,121.5,12,3,0.800,41.9,...,81.9,10.3,32.5,42.7,25.9,12.1,7.1,4.9,16.5,9.7
1,BOSTON CELTICS,2023-24,2023-24,82,48.4,120.6,64,18,0.780,43.9,...,80.7,10.7,35.6,46.3,26.9,11.9,6.8,6.6,16.2,11.3
2,BOSTON CELTICS,2022-23,2022-23,82,48.7,117.9,57,25,0.695,42.2,...,81.2,9.7,35.6,45.3,26.7,13.4,6.4,5.2,18.8,6.5
3,BOSTON CELTICS,2021-22,2021-22,82,48.5,111.8,51,31,0.622,40.7,...,81.6,10.5,35.5,46.1,24.8,13.6,7.2,5.8,18.5,7.3
4,BOSTON CELTICS,2020-21,2020-21,72,48.3,112.6,36,36,0.500,41.5,...,77.5,10.6,33.6,44.3,23.5,14.1,7.7,5.3,20.4,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,SAN ANTONIO SPURS,2000-01,2000-01,82,48.4,96.2,58,24,0.707,35.2,...,71.5,11.0,33.1,44.1,21.7,14.0,6.9,7.0,18.9,7.8
858,SAN ANTONIO SPURS,1999-00,1999-00,82,48.4,96.2,53,29,0.646,36.0,...,74.6,11.3,32.5,43.8,22.2,15.0,7.5,6.7,20.9,5.9
859,SAN ANTONIO SPURS,1998-99,1998-99,50,48.3,92.8,37,13,0.740,34.8,...,69.8,12.3,31.7,44.0,22.0,15.2,8.4,7.0,20.2,8.1
860,SAN ANTONIO SPURS,1997-98,1997-98,82,48.4,92.5,56,26,0.683,35.3,...,68.8,12.0,32.2,44.2,22.4,16.1,6.3,6.9,21.1,4.0
861,SAN ANTONIO SPURS,1996-97,1997-98,82,48.4,92.5,56,26,0.683,35.3,...,68.8,12.0,32.2,44.2,22.4,16.1,6.3,6.9,21.1,4.0

In [122]:
nba_team_stats['Team Name'].nunique()

30